# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e5c07c860855f087e6ff6d88ddbe3faec3d977f73dba5d7ed7275650e683c7e2ea9e6b35cfe34c7a412ad1ca300827f62612e5d26fab11bf0f89022305c84641

test:
  secret_key_base: de175106d23cf09e52098d1b81c9e43eebcd3fd5f1a14bb52cc2d815a8736754e7bf9e838f3329c50a346e7b84c3a3373545a45ac76d11ae52a6e350f7ab87c5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
